// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCBMZwUuIXJJW3Ko0rKKizScHeSVqcnJo',
    appId: '1:654550918154:web:009ef0b295e4f13bea6bf3',
    messagingSenderId: '654550918154',
    projectId: 'fnf-fitness',
    authDomain: 'fnf-fitness.firebaseapp.com',
    storageBucket: 'fnf-fitness.appspot.com',
    measurementId: 'G-YDVQ3GCXJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXv_j7C2pNwhvAmWOumhAHjLdoLGD7I-w',
    appId: '1:654550918154:android:93c0293aabcfc386ea6bf3',
    messagingSenderId: '654550918154',
    projectId: 'fnf-fitness',
    storageBucket: 'fnf-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuH6qLLezF3IoV32CgCG7-oTVAhKimM1U',
    appId: '1:654550918154:ios:48e3414d6418307cea6bf3',
    messagingSenderId: '654550918154',
    projectId: 'fnf-fitness',
    storageBucket: 'fnf-fitness.appspot.com',
    iosBundleId: 'com.example.fnfFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuH6qLLezF3IoV32CgCG7-oTVAhKimM1U',
    appId: '1:654550918154:ios:71224d412c3f29baea6bf3',
    messagingSenderId: '654550918154',
    projectId: 'fnf-fitness',
    storageBucket: 'fnf-fitness.appspot.com',
    iosBundleId: 'com.example.fnfFitness.RunnerTests',
  );
}
